# Generated by Django 3.2.12 on 2023-04-27 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('number', models.PositiveIntegerField(default=1)),
                ('life', models.CharField(max_length=127)),
            ],
            options={
                'verbose_name': 'планета',
                'verbose_name_plural': 'планеты',
            },
        ),
    ]
